name: internhs
description: "Help all high schoolers get the intership they dream of"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_gradient_text: 1.3.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  flutter_gradient_animation_text: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/internhs-header.png
    - lib/assets/images/landing-vector.png
    - lib/assets/images/auth_background.png
  fonts:
    - family: Lora
      fonts:
        - asset: lib/assets/fonts/Lora/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: SchibstedGrotesk
      fonts:
        - asset: lib/assets/fonts/Schibsted_Grotesk/SchibstedGrotesk-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-SemiBold.otf
    - family: Questral
      fonts:
        - asset: lib/assets/fonts/Questrial/Questrial-Regular.ttf
